version: '2'
services:
  sqldata:
    image: busybox
    volumes:
      - ./data/mariadb:/var/lib/mysql
  wwwdata:
    image: busybox
    volumes:
      - ./data/www:/var/www/html
  php-apache:
    build:  ./php-apache
    ports:
      - '80:80'
    volumes:
      - ./php-apache/apache2.conf:/etc/apache2/apache2.conf
      - ./php-apache/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
      - wwwdata
    depends_on:
      - 'mariadb'
  mariadb:
    build:  ./mariadb
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    volumes_from:
      - sqldata
    environment:
      MYSQL_ROOT_PASSWORD:  "toor"
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      TZ: "Asia/Tokyo"
