version: '2'
services:
  sqldata:
    image: busybox
    volumes:
      - ./data/mariadb:/var/lib/mysql
  wwwdata:
    image: busybox
    volumes:
      - ./data/www:/usr/local/apache2/htdocs
  apache:
    build:  ./apache
    ports:
      - '80:80'
    links:
      - 'php7'
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    volumes_from:
      - wwwdata
  php7:
    build:  ./php7
    links:
      - mariadb
    volumes:
      - ./php7/php.ini:/usr/local/etc/php/php.ini
    volumes_from:
      - wwwdata
    depends_on:
      - 'mariadb'
  mariadb:
    build:  ./mariadb
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
    volumes_from:
      - sqldata
    environment:
      MYSQL_ROOT_PASSWORD:  "toor"
      MYSQL_DATABASE: "docker"
      MYSQL_USER: "docker"
      MYSQL_PASSWORD: "docker"
      TZ: "Asia/Tokyo"
